/**
 * Shared venue-photo resolution, used by both VenueGallery (the hero slider)
 * and the venue page's own background-photo treatment, so they always agree
 * on the same source of truth. Priority order:
 *   1. public/venue-photos/<slug>/ -- drop image files in here, they win automatically
 *   2. `photos` override -- manual URL list (legacy)
 *   3. src/data/venue-photos.json -- Google Places auto-fetch (generated by fetch-venue-photos.mjs)
 */
import venuePhotos from '../data/venue-photos.json';
import fs from 'node:fs';
import path from 'node:path';

const PLACES_KEY = 'AIzaSyAfgZvvM4cJxLg9vhi0xPkZSTn6OIWLi8M';
const IMAGE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif']);

export function getVenuePhotos(slug: string, photos?: string[]): string[] {
  let folderImgs: string[] = [];
  try {
    const dir = path.join(process.cwd(), 'public', 'venue-photos', slug);
    const files = fs.readdirSync(dir)
      .filter((f) => IMAGE_EXT.has(path.extname(f).toLowerCase()))
      .sort((a, b) => a.localeCompare(b));
    folderImgs = files.map((f) => `/venue-photos/${slug}/${f}`);
  } catch {
    // folder doesn't exist yet -- fall through to other sources
  }

  const photoData = venuePhotos as Record<string, string[]>;
  const refs = photoData[slug] ?? [];

  return folderImgs.length
    ? folderImgs
    : photos?.length
    ? photos
    : refs.length
    ? refs.map((name) => `https://places.googleapis.com/v1/${name}/media?maxWidthPx=900&key=${PLACES_KEY}`)
    : [];
}
